services:
  postgres:
    image: postgres:16
    container_name: order-manager-postgres
    environment:
      POSTGRES_DB: order_manager
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: