services:
  postgres:
    image: postgres:16
    container_name: order-manager-postgres
    environment:
      POSTGRES_DB: order_manager
      POSTGRES_USER: order_manager
      POSTGRES_PASSWORD: Testes2026@
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tomcat:
    build: .
    container_name: order-manager-tomcat
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      JAVA_TOOL_OPTIONS: >-
       -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
volumes:
  postgres_data: