mail.enabled=false

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

mail.username=macuacuafrancisco@gmail.com
mail.password=Testes2026@
mail.from=macuacuafrancisco@gmail.com